import { Sparkle } from "lucide-react";
import { cn } from "@/lib/utils";

export function AiBadge({
  label = "Generated by WorkFlowAI",
  className,
}: {
  label?: string;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border border-ai/25 bg-ai-soft px-2.5 py-1 text-[0.6875rem] font-semibold text-ai",
        className,
      )}
    >
      <Sparkle className="!size-3" />
      {label}
    </span>
  );
}

export function AiDot({ className }: { className?: string }) {
  return (
    <span className={cn("relative inline-flex size-2 items-center justify-center", className)}>
      <span className="ai-dot absolute inset-0 rounded-full bg-ai" />
    </span>
  );
}
